config/routes.rb
Rails.application.routes.draw do

  root 'bookmarks#top'

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  
  get 'search/search'
  get '/search' => 'search#search'

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations',
    passwords: 'customers/passwords'
  }

  namespace :customers do
    get 'confirm' => 'customers#confirm'
    patch 'hide' => 'customers#hide'
    put 'hide' => 'customers#hide'
  end

  scope module: :customers do
    resources :customers, only: [:show, :edit, :update] do
    resources :favorites, only: [:index ]
    end
  end

  resources :bookmarks do
    
    resource :favorites, only: [:create, :destroy ]
    resource :bookmark_comments, only: [:index, :edit, :destroy, :update, :create ]
    resource :genres, only: [:create, :update, :destroy]
    collection {post :import}
  end

  resources :relationships, only: [:create, :destroy]

  get 'follower/:id' => 'relationships#follower', as: 'follower'
  get 'followed/:id' => 'relationships#followed', as: 'followed'

  resources :folders, only: [:show, :edit, :create, :destroy, :update]
  resources :folder_bookmarks, only: [:create,:destroy,:update]


  devise_for :admins, controllers: {
          sessions: 'admins/sessions'
        }
    namespace :admins do
        get '/' => 'admins#top'
        resources :bookmarks, only: [:show,:index,:edit, :update]
        resources :genres, only: [:index,:create, :edit, :update]
        resources :customers, only: [:show,:index,:edit, :update]
        resources :bookmark_comments, only: [:index, :show, :update, :destroy]
    end

  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :customer
  belongs_to :bookmark

end

app/controllers/customers/favorites_controller.rb
class Customers::FavoritesController < ApplicationController

  def index
    @customer = Customer.find(params[:customer_id])
    # @bookmarks = Bookmark.where(customer_id: @customer.id).all
    @favorites = @customer.favorites
  end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    favorite = current_customer.favorites.new(bookmark_id: @bookmark.id)
    favorite.save
  end

  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    favorite = current_customer.favorites.find_by(bookmark_id: @bookmark.id)
    favorite.destroy
  end

  

end

app/helpers/customers/favorites_helper.rb
module Customers::FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if current_customer.blank? %>
	<%= link_to bookmark_favorites_path(bookmark.id), method: :post, remote: true do %>
		<i class="fa fa-heart" aria-hidden="true"></i>
		<%= bookmark.favorites.count %>
	<% end %>
<% else %>
	<% if bookmark.favorited_by?(current_customer) %>
		<%= link_to bookmark_favorites_path(bookmark.id), method: :delete, remote: true do %>
			<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
			<%= bookmark.favorites.count %>
		<% end %>
	<% else %>
		<%= link_to bookmark_favorites_path(bookmark.id), method: :post, remote: true do %>
			<i class="fa fa-heart" aria-hidden="true"></i>
			<%= bookmark.favorites.count %>
		<% end %>
	<% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @bookmark.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {bookmark: @bookmark}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @bookmark.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {bookmark: @bookmark}) %>");