config/routes.rb
Rails.application.routes.draw do

  root 'bookmarks#top'

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  
  get 'search/search'
  get '/search' => 'search#search'

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations',
    passwords: 'customers/passwords'
  }

  namespace :customers do
    get 'confirm' => 'customers#confirm'
    patch 'hide' => 'customers#hide'
    put 'hide' => 'customers#hide'
  end

  scope module: :customers do
    resources :customers, only: [:show, :edit, :update] do
    resources :favorites, only: [:index ]
    end
  end

  resources :bookmarks do
    
    resource :favorites, only: [:create, :destroy ]
    resource :bookmark_comments, only: [:index, :edit, :destroy, :update, :create ]
    resource :genres, only: [:create, :update, :destroy]
    collection {post :import}
  end

  resources :relationships, only: [:create, :destroy]

  get 'follower/:id' => 'relationships#follower', as: 'follower'
  get 'followed/:id' => 'relationships#followed', as: 'followed'

  resources :folders, only: [:show, :edit, :create, :destroy, :update]
  resources :folder_bookmarks, only: [:create,:destroy,:update]


  devise_for :admins, controllers: {
          sessions: 'admins/sessions'
        }
    namespace :admins do
        get '/' => 'admins#top'
        resources :bookmarks, only: [:show,:index,:edit, :update]
        resources :genres, only: [:index,:create, :edit, :update]
        resources :customers, only: [:show,:index,:edit, :update]
        resources :bookmark_comments, only: [:index, :show, :update, :destroy]
    end

  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @model = params["search"]["model"]
    @content = params["search"]["content"]
    @how = params["search"]["how"]
    @datas = search_for(@how, @model, @content)
  end

  private
  def match(model, content)
    if model == 'customer'
      Customer.where(name: content)
    elsif model == 'bookmark'
      Bookmark.where(title: content)
    end
  end

  def partical(model, content)
    if model == 'customer'
      Customer.where("customer_name LIKE ?", "%#{content}%")
    elsif model == 'bookmark'
      Bookmark.where("bookmark_name LIKE ?", "%#{content}%")
    end
  end

  def search_for(how, model, content)
    case how
    when 'match'
      match(model, content)
    when 'partical'
      partical(model, content)
    end
  end
end

app/views/search/search.html.erb
<table class="table">
  <% if @model == 'customer' %>
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th>follows</th>
        <th>followers</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <% @datas.each do |customer| %>
      <tr>
        <td><%= attachment_image_tag(customer, :customer_image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
        <td><%= customer.customer_name %></td>
        <td><%= customer.followed.count %></td>
        <td><%= customer.follower.count %></td>
        <td><%= link_to 'Show', customer %></td>
      </tr>
    <% end %>
  <% else %>
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <% @datas.each do |bookmark| %>
      <tr>
        <td>
          <%= link_to(bookmark.customer) do %>
            <%= attachment_image_tag(bookmark.customer, :customer_image, :fill, 50, 50, fallback: "no_image.jpg") %>
          <% end %>
        </td>
        <td><%= bookmark.bookmark_name %></td>
        <td><%= bookmark.bookmark_description %></td>
        <td><%= link_to 'Show', bookmark_path(bookmark.id) %></td>
      </tr>
    <% end %>
  <% end %>
</table>