config/routes.rb
Rails.application.routes.draw do

  root 'bookmarks#top'

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  
  get 'search/search'
  get '/search' => 'search#search'

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations',
    passwords: 'customers/passwords'
  }

  namespace :customers do
    get 'confirm' => 'customers#confirm'
    patch 'hide' => 'customers#hide'
    put 'hide' => 'customers#hide'
  end

  scope module: :customers do
    resources :customers, only: [:show, :edit, :update] do
    resources :favorites, only: [:index ]
    end
  end

  resources :bookmarks do
    
    resource :favorites, only: [:create, :destroy ]
    resource :bookmark_comments, only: [:index, :edit, :destroy, :update, :create ]
    resource :genres, only: [:create, :update, :destroy]
    collection {post :import}
  end

  resources :relationships, only: [:create, :destroy]

  get 'follower/:id' => 'relationships#follower', as: 'follower'
  get 'followed/:id' => 'relationships#followed', as: 'followed'

  resources :folders, only: [:show, :edit, :create, :destroy, :update]
  resources :folder_bookmarks, only: [:create,:destroy,:update]


  devise_for :admins, controllers: {
          sessions: 'admins/sessions'
        }
    namespace :admins do
        get '/' => 'admins#top'
        resources :bookmarks, only: [:show,:index,:edit, :update]
        resources :genres, only: [:index,:create, :edit, :update]
        resources :customers, only: [:show,:index,:edit, :update]
        resources :bookmark_comments, only: [:index, :show, :update, :destroy]
    end

  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/folder.rb
class Folder < ApplicationRecord

  belongs_to :customer

  # has_many :folder_bookmark_relations
  has_many :bookmarks # , through: :folder_bookmark_relations

	validates :folder_name, presence: true, length: {maximum: 30, minimum: 2}


end

app/controllers/customers/folders_controller.rb
class Customers::FoldersController < ApplicationController
  def create
  end

  def destroy
  end

  def update
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController

  def show
    @folder = Folder.find(params[:id])
    @newfolder = Folder.new
    @bookmarks = @folder.bookmarks
    @newbookmark = Bookmark.new
    @customer = @folder.customer
    @folders = current_customer.folders
  end

  def edit
    @folder = Folder.find(params[:id])
  end

  def create
  	@newfolder = Folder.new(folder_params)
  	@newfolder.customer_id = current_customer.id
    @customer = current_customer
    if @newfolder.save #入力されたデータをdbに保存する。
      redirect_to customer_path(@customer.id), notice: "successfully created folder!"#保存された場合の移動先を指定。
    else
      @folders = current_customer.folders
      @newbookmark = Bookmark.new
      @bookmarks = current_customer.bookmarks
      render "customers/customers/show"
    end
  end


  def update
    @folder = Folder.find(params[:id])
    if @folder.update(folder_params)
      redirect_to customer_path(@customer.id), notice: "successfully updated folder!"
    else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
      render "edit"
    end
  end

  def destroy
    @folder = Folder.find(params[:id])
    @folder.destroy
    @customer = current_customer
    redirect_to customer_path(@customer.id), noticefolder: "successfully delete folder!"
  end


  private
  def folder_params
    params.require(:folder).permit(:folder_name, :pearent_folder_id)
  end

end

app/helpers/customers/folders_helper.rb
module Customers::FoldersHelper
end

app/views/folders/_error_messages.html.erb
<% if folder.errors.any? %>
	<div id="error_explanation">
	  <font color="red">
	    <h2><%= pluralize(folder.errors.count, "error") %> prohibited this folder from being saved:</h2>
	    <ul>
	      <% folder.errors.full_messages.each do |message| %>
	      	<li><%= message %></li>
	      <% end %>
	    </ul>
	  </font>
	</div>
<% end %>

app/views/folders/_folders_index.html.erb
<h4>Folder index</h4>
<table class="table table-hover table-inverse">
  <% folders.each do |folder| %>
	  <tr>
	    <td><%= link_to folder.folder_name, folder_path(folder.id) %></td>
	    <td><%=  %></td>
	    <td>
	      <%= link_to "", folder_path(folder.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "delete-button far fa-times-circle color:red destroy_folder_#{folder.id}" %>
	    </td>
	  </tr>
  <% end %>
</table>

app/views/folders/_newfolder.html.erb
<h4>New Folder</h4>
<%= form_for @newfolder do |f| %>
	<div class="field row">
	  <%= f.label :フォルダ新規作成 %>
	  <%= f.text_field :folder_name, class: "col-xs-8 col-xs-offset-1 book_title" %>
	  <%= f.submit "登録", class: "btn btn-primary col-xs-2 text-center" %>
	</div>
<% end %>

app/views/folders/create.html.erb
<h1>Customers::Folders#create</h1>
<p>Find me in app/views/customers/folders/create.html.erb</p>

app/views/folders/destroy.html.erb
<h1>Customers::Folders#destroy</h1>
<p>Find me in app/views/customers/folders/destroy.html.erb</p>

app/views/folders/edit.html.erb
<h2>フォルダ編集画面</h2>
<%= form_for @folder, url:customer_path(@customer.id) do |f| %>
	<%= f.label :フォルダ %>
	<%= f.text_field :folder_name %>
	<%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/folders/show.html.erb
<h2></h2>

<div class="row">
  <%= render "bookmarks/error_messages", bookmark: @newbookmark %>
  <%= render "folders/error_messages", folder: @newfolder %>
  <div class="col-xs-3">
    <div class="row">
      <table class="table table-hover">
        <tr>
          <%= attachment_image_tag(@customer, :customer_image, :fill, 200, 200, fallback: "no_image.jpg") %>
        </tr>
        <tr>
          <th>name</th>
          <th><%= @customer.customer_name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @customer.customer_introduction %></th>
        </tr>
        <tr>
          <th>follows</th>
          <th><%= link_to "#{@customer.follower.count} ", followed_path(@customer.id) %></th>
        </tr>
        <tr>
          <th>followers</th>
          <th><%= link_to @customer.followed.count , follower_path(@customer.id) %></th>
        </tr>
      </table>
      <%= render "relationships/follow_button", customer: @customer %>

      <%= link_to '',edit_customer_path(@customer), class: "col-xs-8 col-xs-offset-2 text-center btn btn-default glyphicon glyphicon-wrench edit_user_#{@customer.id}" %>
    </div>
    <div class="row">
      <h4>New Folder</h4>
      <%= form_for @newfolder do |f| %>
        <div class="field row">
          <%= f.label :フォルダ新規作成 %>
          <%= f.text_field :folder_name, class: "col-xs-8 col-xs-offset-1 book_title" %>
          <%= f.submit "登録", class: "btn btn-primary col-xs-2 text-center" %>
        </div>
      <% end %>
    </div>

    <div class="row">
      <h4>Folder index</h4>
      <table class="table table-hover table-inverse">
        <% @folders.each do |folder| %>
          <tr>
            <td><%= link_to folder.folder_name, folder_path(folder.id) %></td>
            <td><%=  %></td>
            <td>
              <%= link_to "", folder_path(folder.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "delete-button far fa-times-circle color:red destroy_folder_#{folder.id}" %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class="col-xs-9">
    <h3>New bookMark</h3>
    <%= form_for(@newbookmark) do |f| %>
      <div class="field row">
        <%= f.label :ブックマークするページのURLを入力してください %>
        <%= f.text_field :bookmark_url, class: "col-xs-10 book_title" %>
        <%= f.submit "登録", class: "btn btn-primary col-xs-2 text-center" %>
      </div>
    <% end %>

    <h3>BookMarks</h3>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>サイト画面</th>
          <th>Title/URL</th>
          <th>Opinion</th>
          <th colspan="3">公開状況</th>
        </tr>
      </thead>
      <tbody>
          <% @bookmarks.each do |bookmark| %>
            <%= render "customers/customers/customer_bookmark_index", bookmark: bookmark %>
          <% end %>
        </tbody>
    </table>
  </div>
</div>

app/views/folders/update.html.erb
<h1>Customers::Folders#update</h1>
<p>Find me in app/views/customers/folders/update.html.erb</p>