config/routes.rb
Rails.application.routes.draw do

  root 'bookmarks#top'

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  
  get 'search/search'
  get '/search' => 'search#search'

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations',
    passwords: 'customers/passwords'
  }

  namespace :customers do
    get 'confirm' => 'customers#confirm'
    patch 'hide' => 'customers#hide'
    put 'hide' => 'customers#hide'
  end

  scope module: :customers do
    resources :customers, only: [:show, :edit, :update] do
    resources :favorites, only: [:index ]
    end
  end

  resources :bookmarks do
    
    resource :favorites, only: [:create, :destroy ]
    resource :bookmark_comments, only: [:index, :edit, :destroy, :update, :create ]
    resource :genres, only: [:create, :update, :destroy]
    collection {post :import}
  end

  resources :relationships, only: [:create, :destroy]

  get 'follower/:id' => 'relationships#follower', as: 'follower'
  get 'followed/:id' => 'relationships#followed', as: 'followed'

  resources :folders, only: [:show, :edit, :create, :destroy, :update]
  resources :folder_bookmarks, only: [:create,:destroy,:update]


  devise_for :admins, controllers: {
          sessions: 'admins/sessions'
        }
    namespace :admins do
        get '/' => 'admins#top'
        resources :bookmarks, only: [:show,:index,:edit, :update]
        resources :genres, only: [:index,:create, :edit, :update]
        resources :customers, only: [:show,:index,:edit, :update]
        resources :bookmark_comments, only: [:index, :show, :update, :destroy]
    end

  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/bookmark_comment.rb
class BookmarkComment < ApplicationRecord

  belongs_to :customer
  belongs_to :bookmark
  validates :bookmark_comment, presence: true
  validates :score, numericality:{ greater_than: -0.9 }

end

app/controllers/admins/bookmark_comments_controller.rb
class Admins::BookmarkCommentsController < ApplicationController
  def index
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/controllers/bookmark_comments_controller.rb
class BookmarkCommentsController < ApplicationController

  def index
  end

  def edit
  end

  def update
  end

  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    @bookmark_comment = current_customer.bookmark_comments.new(bookmark_comment_params)
    @bookmark_comment.bookmark_id = @bookmark.id
    @bookmark_comment.score = Language.get_data(bookmark_comment_params[:bookmark_comment])
    if @bookmark_comment.save
    redirect_back(fallback_location: root_path)
    else
    render "bookmarks/show"
    end
  end

  def destroy
    bookmark_comment = BookmarkComment.find(params[:bookmark_comment_id])
    bookmark_comment.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def bookmark_comment_params
      params.require(:bookmark_comment).permit(:bookmark_comment)
  end

end

app/helpers/admins/bookmark_comments_helper.rb
module Admins::BookmarkCommentsHelper
end

app/helpers/customers/bookmark_comments_helper.rb
module Customers::BookmarkCommentsHelper
end

app/views/bookmark_comments/_bookmark_comment_form.html.erb
<%= render "bookmarks/error_messages", bookmark: @bookmark_comment %>
<%= form_for [@bookmark, @bookmark_comment] do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <%= f.text_area :bookmark_comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
    </div>
  </div>
  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

app/views/bookmark_comments/_bookmark_comment_index.html.erb
<% @bookmark.bookmark_comments.each do |bookmark_comment| %>
  <li class="bookmark_comment"><%= bookmark_comment.created_at.strftime('%Y/%m/%d') %>
    <div class="bookmark_comment">
			<%= link_to (bookmark_comment.customer) do %>
				<%= attachment_image_tag(bookmark_comment.customer, :customer_image, :fill, 50, 50, fallback: "no_image.jpg") %><br>
				<%= bookmark_comment.customer.customer_name %>
			<% end %>
			<%= bookmark_comment.bookmark_comment %>
			<%# <%= bookmark_comment.score %>
			<% if bookmark_comment.customer == current_customer %>
				<%= link_to "Destroy", bookmark_bookmark_comments_path(@bookmark, bookmark_comment_id: bookmark_comment.id), method: :delete , class: "btn-sm btn-danger" %>
			<% end %>
    </div>
  </li>
<% end %>